### ISSUE TITLE
Witness generator fails to generate witness (should work)

### ISSUE THREAD

**Issue by leonardoalt** [powdr-labs/powdr#189]
Witgen doesn't work for this, but I think it should. Interestingly, if I change degree to 3 it works. @georgwiese @Schaeff do you have any idea why?

```
machine Bug {
	degree 4;

	reg pc[@pc];
	//reg X[<=];
	reg A;

	instr INC { A' = A + 1 }
	instr DEC { A' = A - 1 }
	instr IS_ZERO { A = 0 }

	function main {
		INC;
		DEC;
		IS_ZERO;
	}
}
```

**Comment by georgwiese** [comment]
The problem is that the pc is increased to 3, but the program consists only of lines 0, 1, and 2. This is the compiled PIL, which is indeed unsatisfiable:

```
namespace main(4);
pol constant first_step = [1] + [0]*;
pol commit pc;
(first_step * A) = 0;
pol commit A;
pol commit instr_INC;
pol commit instr_DEC;
pol commit instr_IS_ZERO;
(instr_IS_ZERO * (A - 0)) = 0;
A' = ((((first_step' * 0) + (instr_INC * (A + 1))) + (instr_DEC * (A - 1))) + ((1 - ((first_step' + instr_INC) + instr_DEC)) * A));
// Increases pc to 3
pc' = ((1 - first_step') * (pc + 1));
pol constant p_line = [0, 1, 2] + [2]*;
pol constant p_instr_DEC = [0, 1, 0] + [0]*;
pol constant p_instr_INC = [1, 0, 0] + [0]*;
pol constant p_instr_IS_ZERO = [0, 0, 1] + [1]*;
// Fails for p = 3
{ pc, instr_INC, instr_DEC, instr_IS_ZERO } in { p_line, p_instr_INC, p_instr_DEC, p_instr_IS_ZERO };
```

I guess for a program of length n, you need an execution trace of size n + 1, because you want it to include the initial state and all n states. And because of that you always need to finish with an infinite loop?

**Comment by leonardoalt** [comment]
Yea I actually thought we always added the infinite loop automatically, but that's done only for Rust. So yea this this fine.
