### ISSUE TITLE
Cli not support proof  verify？

### ISSUE THREAD

**Issue by godeamon** [powdr-labs/powdr#863]
Hello:
Why powdr command not support proof verify？How should I verify the proof？

**Comment by leonardoalt** [comment]
Hi @godeamon ! Currently verification is done by using each proof library directly in Rust since the proof can be requested that way and the libraries are external, but I agree CLI should also support it. I created https://github.com/powdr-labs/powdr/issues/890 to track that.

I'm closing this issue since the feature issue is now open, but feel free to reopen if needed.
